# Generated by Django 5.1.2 on 2025-04-04 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENQUIRY', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenquiry',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='studentenquiry',
            name='mobile',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
